services:
  app:
    container_name: spring-boot-app
    image: ${DOCKER_IMAGE}
    ports:
      - "8080:8080"
    restart: always
    environment:
      # application.yml의 ${DB_URL} 등과 매핑
      DB_URL: ${SPRING_DATASOURCE_URL}
      DB_USER_NAME: ${SPRING_DATASOURCE_USERNAME}
      DB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # JWT 설정 매핑 (yml의 이름과 일치시킴)
      JWT_SECRET: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS: ${JWT_EXPIRATION_ACCESS}

      # OAuth2 설정 (필요시 추가)
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Redis 설정
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always